---
title: "covid_period_kl_analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{covid_period_kl_analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(acsprojectns)
library(devtools)
library(dplyr)
library(tidyr)
library(purrr)
library(lubridate)
library(kableExtra)
library(survival)
library(survminer)
library(wesanderson)
library(viridis)
library(icdb)

load_all()
icdb::use_cache(TRUE)
if(.Platform$OS.type == "unix") {
  msrv <- icdb::mapped_server(config  = system.file("database_connections", "home", "mysql.yaml", package="acsprojectns"),
                              mapping = system.file("database_connections", "home", "mapping.yaml", package="acsprojectns"))
}else if (.Platform$OS.type == "windows") {
  msrv <- icdb::mapped_server("XSW",
                              mapping = system.file("database_connections", "work", "mapping.yaml", package="acsprojectns"))
}
adm_method_codes <- system.file("admission_method_codes/admission_method_codes.csv", package="acsprojectns")
adm_method <- acsprojectns::get_codes(adm_method_codes) |>
  mutate(admission_method = dplyr::case_when(grepl("emergency", admission_method_description) ~ "emergency",
                                             grepl("elective", admission_method_description) ~ "elective",
                                             TRUE ~ "other")) |>
  select(admission_method_code, admission_method)
icd10_codes_fp <- system.file("icd10_codes/covid_period_kl_analysis_icd10_codes.csv", package="acsprojectns")
icd10_codes    <- acsprojectns::get_codes(icd10_codes_fp) |> filter(!is.na(code))
```

```{r cohort}
start <- as.Date("2016-07-01") 
end   <- as.Date("2023-07-01") 


# define any diagnosis code, regardless of position
# cohort <- msrv$sus$apc_spells_diagnosis |>
#   filter(spell_start >= start & spell_end <= end) %>%
#   icdb::run() |>
#   mutate(across(matches("nhs_number|primary_diagnosis_icd|secondary_diagnosis_[0-9]+_icd"), as.character), 
#          month_yr = format_ISO8601(spell_start, precision = "ym")) |>
#   filter(if_any(matches("primary_diagnosis_icd|secondary_diagnosis_[0-9]+_icd"), ~ . %in% icd10_codes$code)) |>
#   pivot_longer(matches("(primary|secondary)_diagnosis_[0-9_]*icd"), 
#                names_to="diag_pos", 
#                values_to="diagnosis", 
#                values_drop_na=TRUE) |>
#   left_join(icd10_codes, by=c("diagnosis"="code")) |>
#   filter(!is.na(group))

# look at ?Takotsubo specifically
# cohort <- msrv$sus$apc_spells_diagnosis |>
#   filter(spell_start >= start & spell_end <= end) %>%
#   icdb::run() |>
#   mutate(across(matches("nhs_number|primary_diagnosis_icd|secondary_diagnosis_[0-9]+_icd"), as.character),
#          month_yr = format_ISO8601(spell_start, precision = "ym")) |>
#   filter(if_any(matches("primary_diagnosis_icd|secondary_diagnosis_[0-9]+_icd"), ~ . %in% icd10_codes$code)) |>
#   pivot_longer(matches("secondary_diagnosis_[0-9_]*icd"),
#                names_to="diag_pos",
#                values_to="diagnosis",
#                values_drop_na=TRUE) |>
#   left_join(icd10_codes, by=c("diagnosis"="code")) |>
#   filter(!is.na(group))
# primary_icd_with_I518_secondary = cohort |> filter(diagnosis=="I518") |> group_by(primary_diagnosis_icd) |> summarise(n=n()) |> arrange(desc(n)) |> left_join(icd10_codes, by=c("primary_diagnosis_icd"="code"))
# write.csv(primary_icd_with_I518_secondary, paste0(system.file("extdata", "figures", "for_KL", package="acsprojectns"), "/", "primary_icd_code_counts_when_I518_is_a_secondary_code_jul16_jul23.csv"), row.names=FALSE)


# define only if in primary position
cohort <- msrv$sus$apc_spells_diagnosis |>
  filter(spell_start >= start & spell_end <= end) %>%
  icdb::run() |>
  mutate(across(matches("nhs_number|primary_diagnosis_icd"), as.character),
         month_yr = format_ISO8601(spell_start, precision = "ym")) |>
  filter(if_any(matches("primary_diagnosis_icd"), ~ . %in% icd10_codes$code)) |>
  pivot_longer(matches("primary_diagnosis_icd"),
               names_to="diag_pos",
               values_to="diagnosis",
               values_drop_na=TRUE) |>
  left_join(icd10_codes, by=c("diagnosis"="code")) |>
  filter(!is.na(group))



by.icd10 <- cohort |> 
  group_by(diagnosis, month_yr) |>
  summarise(n = length(unique(nhs_number)))
write.csv(by.icd10, paste0(system.file("extdata", "figures", "for_KL", package="acsprojectns"), "/", "counts_by_icd10.csv"), row.names=FALSE)

total_icd10_codes <- by.icd10 |> 
  group_by(diagnosis) |> 
  summarise(count=sum(n, na.rm = T)) |> 
  left_join(icd10_codes, by=c("diagnosis"="code"))
write.csv(total_icd10_codes, paste0(system.file("extdata", "figures", "for_KL", package="acsprojectns"), "/", "counts_total_icd10_jul16_jul23.csv"), row.names=FALSE)

ggplot(cohort, aes(x=lubridate::ym(month_yr), fill=diagnosis)) +
  geom_bar(stat="count", colour="black") +
  theme_minimal() +
  scale_fill_viridis_d(begin=0, end=1) +
  labs(title = "Cardiac presentations across COVID-19 era", subtitle = "July 2016 - July 2023", fill = "" ) +
  ylab("Count") +
  xlab("Date") +
  scale_x_date(date_labels="%b %Y") + 
  facet_wrap(~diagnosis, scales = "free")




by.fine_group <- cohort |> 
  group_by(description_simple, month_yr) |>
  summarise(n = length(unique(nhs_number)))
write.csv(by.fine_group, paste0(system.file("extdata", "figures", "for_KL", package="acsprojectns"), "/", "counts_by_fine_group.csv"), row.names=FALSE)

total_fine_group <- by.fine_group |> 
  group_by(description_simple) |> 
  summarise(count=sum(n, na.rm = T))
write.csv(total_fine_group, paste0(system.file("extdata", "figures", "for_KL", package="acsprojectns"), "/", "counts_total_fine_group_jul16_jul23.csv"),row.names=FALSE)


ggplot(cohort, aes(x=lubridate::ym(month_yr), fill=description_simple)) +
  geom_bar(stat="count", colour="black") +
  theme_minimal() +
  scale_fill_viridis_d(begin=0, end=1) +
  labs(title = "Cardiac presentations across COVID-19 era", subtitle = "July 2016 - July 2023", fill = "" ) +
  ylab("Count") +
  xlab("Date") +
  scale_x_date(date_labels="%b %Y", date_breaks = "1 year") + 
  facet_wrap(~description_simple, scales = "free")
 




by.broad_group <- cohort |> 
  group_by(group, month_yr) |>
  summarise(n = length(unique(nhs_number)))
write.csv(by.broad_group, paste0(system.file("extdata", "figures", "for_KL", package="acsprojectns"), "/", "counts_by_broad_group.csv"), row.names=FALSE)

total_broad_group <- by.broad_group |> 
  group_by(group) |> 
  summarise(count=sum(n, na.rm = T))
write.csv(total_broad_group, paste0(system.file("extdata", "figures", "for_KL", package="acsprojectns"), "/", "counts_total_broad_group_jul16_jul23.csv"),row.names=FALSE)

ggplot(cohort, aes(x=lubridate::ym(month_yr), fill=group)) +
  geom_bar(stat="count", colour="black") +
  theme_minimal() +
  scale_fill_viridis_d(begin=0, end=1) +
  labs(title = "Cardiac presentations across COVID-19 era", subtitle = "July 2016 - July 2023", fill = "" ) +
  ylab("Count") +
  xlab("Date") +
  scale_x_date(date_labels="%b %Y", date_breaks = "1 year") + 
  facet_wrap(~group, scales = "free")




```
