---
title: BNSSG Acute Coronary Syndrome Project
author: Nicholas Sunderland
output: 
  pdf_document: 
    highlight: pygments # kate/pygments/haddock
    number_sections: yes
    toc: yes
    toc_depth: 2
#bibliography: /Users/nicholassunderland/git/thesis/bibliography/phd_proposal.bib
csl: https://www.zotero.org/styles/nature
link-citations: true
reference-section-title: References
header-includes:
- \usepackage{fvextra}
- \usepackage[htt]{hyphenat}
- \let\NormalTok\texttt
- \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaksymbolleft={}, showspaces=false, showtabs = false, breaklines, breakanywhere, breaksymbol=, breakanywheresymbolpre=, commandchars=\\\{\}}
---
```{=tex}
\listoffigures
\listoftables
\newpage
```
```{r setup, include=FALSE}

# Plan 
# demographics at index ACS
#     age, sex, ethnicity, comorbidities, frailty measures, IMD, employment, income
#     split by frailty, age, type of ACS
# index ACS details 
#     type of ACS, admission length, ICU stay, procedures
#     split by frailty
# subsequent events
#     death, MACCE, bleeding, any hospital admission
#     split by frailty, age, type of ACS
#     overlaid KM curves for 1st hospital admission, 2nd, 3rd, 4th etc (decreasing demominator in each)
# cost over time
#     stacked cost by macro service
#     cost as % of cohort
#     secondary care cost by secondary care type and then by i/p service
#     split by frailty

# end

knitr::opts_chunk$set(
  tidy="styler",
  collapse=TRUE,
  comment="#>",
  echo=FALSE, 
  results = 'hide',
  error=FALSE,
  warning=FALSE,
  message=FALSE
)

flag <- "home" #bnssg

# HOW TO GUIDE
# https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf
```
```{r child = 'introduction.Rmd'}
```
```{=tex}
\newpage
```
```{r child = 'methods.Rmd'}
```
```{=tex}
\newpage
```
```{r child = 'demographics.Rmd'}
```
```{=tex}
\newpage
```
```{r child = 'index_event.Rmd'}
```
```{=tex}
\newpage
```
```{r child = 'survival.Rmd'}
```
```{=tex}
\newpage
```



